-- 20260923103041_admin_auth_grants.down.sql

ALTER DEFAULT PRIVILEGES IN SCHEMA admin_auth
  REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM admin_role;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA admin_auth FROM admin_role;
REVOKE USAGE ON SCHEMA admin_auth FROM admin_role;
